### ISSUE TITLE
Support custom Cache-Control headers

### ISSUE THREAD

**Issue by ptyagii** [3scale/cors-proxy#1]
One of the customers reported high latency issue when the request goes to the apidocs proxy. 
Is it possible to support custom Cache-control headers through the cors proxy? 
Currently apidocs proxy sets Cache-Control header to no-cache. 

Let me know if you need any further details. 

cc @kevprice83

**Comment by mikz** [comment]
This proxy does not set any headers and just transfers what was received from upstream. If the client is adding those headers please report the issue in different component.
